slinkity/slinkity

utils/plugins/snowpackServerPlugin/index.js
Replicates the snowpack server config from
https://github.com/snowpackjs/snowpack/blob/002f863d3583b0c75d150b15a330fe1439a306ed/snowpack/src/commands/dev.ts#L1042-L1048
=> Make snowpack config same as `snowpack dev`

package.json, src/plugin/reactPlugin/toRendererHtml.js
Resolves [an issue raised](https://github.com/Holben888/slinkity-home/issues/6) on the (now archived) docs repo.
Inlines all `react` and `react`-related imports, which happen to all be inside `toRendererHtml`. Hooray for abstraction!
=> Refactor: remove react as a peer dependency

.eslintrc.yaml, babel.config.js, package-lock.json, package.json, src/plugin/reactPlugin/__snapshots__/toRendererHtml.test.jsx.snap, src/plugin/reactPlugin/toRendererHtml.js, src/plugin/reactPlugin/toRendererHtml.test.jsx
- adds dev dependencies to use JSX in jest tests: `@babel/preset-react`, `babel-jest`, `react`, `react-dom`
- adds unit + snap tests for `toRendererHtml`
- adds JSdocs
=> Add testing - toRendererHtml

src/plugin/reactPlugin/__snapshots__/toHydrationLoadersApplied.test.js.snap, src/plugin/reactPlugin/index.js, src/plugin/reactPlugin/toHydrationLoadersApplied.js, src/plugin/reactPlugin/toHydrationLoadersApplied.test.js
- moves HTML transform logic to a separate file for testability
- tests that HTML files are untouched when no mount points exist
- tests how eager and lazy loaders are applied with snaps
- tests FS writes for components
Working towards #21
=> Testing - HTML transform

docs/styles/docs.scss, docs/styles/styles.scss
resolves #37 
+ new breakpoint variable `$tablet`, for 860px.
+ the docs layout breaks at this min-width into a multi-column layout
+ the toc is now sticky.
I moved the reused `40px` into a new custom property `--site-gap` and called it that way, because that way reused values show how they are connected to this value. Meaning, the `.docs__nav` `top`-value is that way abstractly connected to the `gap` value of the layout, as is the first `<h1>`'s margin-block-start, etc.
=> Sticky & Responsive Docs TOC

docs/.eleventy.js, docs/package-lock.json, docs/package.json, docs/styles/docs.scss, docs/styles/styles.scss
Closes #38 as described in [this issue](https://github.com/slinkity/slinkity/issues/38):
- adds the `markdown-it-anchor` which allows automatic generation of headline links in an accessible way.
- the plugin is configured in a way that is congruent with [the suggestions of Amber Wilson](https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/#accessibility-check) regarding this issue.
- Links are currently only generated for `<h2>`'s, which can be changed at any time.
- Headline Anchors are transparent until the wrapping element is hovered, or until it receives focus.
=> Headline anchor tags for sections in the docs

docs/styles/docs.scss
+ fixes the layout break caused be the overflowing code blocks 
+ fixes another small issue, in where the main part of the docs didn't fill out its available width
=> fix the quick-docs layout

src/cli/toViteSSR.js, src/cli/vite.js, src/plugin/applyViteHtmlTransform.js, src/plugin/index.js, src/plugin/reactPlugin/1-pluginDefinitions/addPageExtension.js
Resolves #54 
- **Moves Vite server startup to after your first 11ty build.** This allows Vite to prebundle any dependencies used in your build output
- **Adds React + React dependencies to the prebundling steps.** This mirrors [Astro's React renderer](https://github.com/snowpackjs/astro/blob/main/packages/renderers/renderer-react/index.js) and sets us up for renderer plugins (see #55)
- **Uses Vite's rollup build when processing component page frontmatter** _before_ the Vite server is started. This is the best compromise I could find to delay the dev server while still processing `frontMatter` and `getProps` during 11ty's build process. This does mean an initial performance hit on startup, but we'll use `ssrLoadModule` thereafter
=> Fix: Vite entrypoint prebundling

package-lock.json, package.json, src/cli/index.js, src/cli/vite.js
Resolves #77 
- use user's input directory instead of our temporary build directory when resolving aliases
- move _all_ React prebundling logic inside that try / catch. Noticed another issue when attempting a React-less production build!
=> Fix: import aliases on production builds

docs/src/docs/component-shortcodes.md, docs/src/docs/config.md
Adds leading file names to code blocks where possible:
In some parts of the documentation, specifically the config.md, there was no consistency in the usage of leading comments to declare the file that was being "edited" in the code block example.
```js
// slinkity.config.js <- this
```
This just adds that leading comment to the code blocks that I found where it made sense to put it.
=> Unify file name in code blocks

src/plugin/applyViteHtmlTransform.js, src/plugin/index.js
Eleventy sets `outputPath` to `false` when user sets `permalink: false`. So we should check for it.
As per: https://github.com/11ty/eleventy/issues/653
This PR solves #82
=> check for outputPath boolean before applying `endsWith`

src/plugin/reactPlugin/2-pageTransform/__snapshots__/toHydrationLoadersApplied.test.js.snap, src/plugin/reactPlugin/2-pageTransform/toLoaderScript.js
Resolves #85 
We added the component's ID to the default import name. This ensures each import is unique to make ESBuild happy!
Note for the future: this could break if we ever change from a numeric ID system.
=> Fix: multiple shortcodes breaks dev server

.gitignore, .vscode/settings.json, CONTRIBUTING.md
- Adds `react-dom` to the pnpm overrides
- Adds a VSCode `settings.json` file with the ESLint auto-formatting enabled.
closes: #73
=> docs: override react-dom as well as react + vscode format settings

README.md, docs/src/_includes/npm-init-slinkity-snippet.md, docs/src/_includes/value-props.md, docs/src/docs/index.md, docs/src/docs/quick-start.md, docs/src/index.md
Resolves #108 
- add `npm init slinkity` call-out to docs homepage and quick start
- change "Overview" title to "What is Slinkity?" for clarity
- extract value props to a shared snippet so the homepage and docs stay aligned (also tweaked to fully cover our featureset)
- update feature set on overview page based on our current roadmap
=> Docs: rework quick start with new `npm init slinkity`

package-lock.json, package.json, src/cli/eleventy.js, src/cli/toViteSSR.js, src/cli/toViteSSR.test.js, src/plugin/applyViteHtmlTransform.js
Resolves #112 
Resolves #109 
- upgrade to latest Vite version - ensures Vite still finds `scss` imports appended by middleware
- ditch old approach to finding CSS imports. Now crawling the module imports for each component as [recommended by the Vite SSR project](https://github.com/brillout/vite-plugin-ssr/commit/debb9bdbc72d0674066541e39362810d7127b161#diff-5b728e58b78bfac491cdfdb37938c371dba95e164f42748bcec6e5c51db10faeR119-R137)
- inject each imported style as a `<link>` in the `head` -> no more potentially empty `style` tags 👍
=> Fix: resolve CSS imports via ESM

www/.eleventy.js, www/src/docs/index.md, www/src/utils/feature-progress-shortcode.js
Howdy! This pull request is for the feature progress table in the docs. I love the emoji key you've got going on, but I noticed that screenreader users wouldn't be able to jump so easily between the emoji key and the table itself.
To make the experience a little easier for folks using assistive technology, I've introduced a `featureProgress` shortcode that takes the respective emoji and adds a visually-hidden node next to it with the full label from the emoji key — so instead of announcing the ⏳ emoji as just `hourglass`, for instance, screenreaders will announce it as something like `hourglass In progress`.
(I opted not to put an `aria-hidden` on the emojis, since leaving the emojis in would allow folks to still cross-reference the table with the emoji key below it)
=> Add screenreader-friendly labels for feature progress table

www/.eleventy.js, www/styles/_base.scss
When containers such as codeblocks are scrollable, it's generally a good practice to make sure they're tabbable with the keyboard — that way, keyboard navigators can use their arrow keys to scroll left and right.
This PR applies `tabindex="0"` to all `<pre>` tags on the site to make them tabbable, and gives them pink glowy focus styles when they are tabbed.
=> Ensure codeblocks are tabbable

www/src/_layouts/home.njk
I ran an Axe DevTools scan on the slinkity.dev homepage. One issue it flagged was that "all content needed to be contained by landmark elements," and it said that the stuff in the top section — logo, tagline, blockquote, links — weren't in a landmark.
They were in a `<section>` element, which does become a landmark when labelled, but I felt like rather than try to come up with a good label, I'd replace that `<section>` with `<header>`, which describes the function of that piece of the page pretty well.
=> Use <header> element on homepage

www/src/_layouts/docs.njk, www/styles/docs.scss
Here's another accessibility one for you! This one applies `aria-current="page"` to whichever link in the left-hand navbar is the current page. This means that when screenreader users navigate to that link within the navbar, they'll hear something like "Configure your project, link, current" (exact announcement varies amongst screenreaders).
This is basically the screenreader equivalent of your `.active` class for sighted users. On that note, some folks like to target `[aria-current="true"]` for styles instead of an `.active` class to better enforce semantics/accessibility. I haven't done that here, but I'd be happy to do that too if that's something you'd be interested in.
=> Add aria-current to active page link in left-hand nav

www/src/docs/component-pages-layouts.md, www/src/docs/component-shortcodes.md, www/src/docs/import-aliases.md, www/src/docs/index.md, www/src/docs/quick-start.md, www/styles/docs.scss
Axe DevTools picked up that the Slinkity docs had some heading levels out of order. For the most part, this was due to `<h3>`s being used to make certain links look more prominent, rather than to section up the page.
This PR introduces some styles to help make those links just as prominent without using `h3` (and - as a bonus! - without straying from Markdown syntax!). To use these styles put your link in a new line, wrapped in a `<strong>` tag, and make sure there's nothing else on that line. For instance:
```md
...previous paragraph ending here.
**[🐣 See our "quick start" guide →](/docs/quick-start)**
Next paragraph starts here...
```
The link above will be bolded and the same font size as an `h3`.
=> Updating heading order in the docs

www/src/_includes/contributors.njk, www/styles/chunks/_contributor.scss
I noticed that the contributors table was using `<h4>` elements to give contributor usernames extra prominence. Since the `h4`s weren't being used for sectioning, I've removed the `h4`s around the username links and given the username links `display: block;`, `font-weight: bold`, and the appropriate margins to emulate the same appearance those links had inside an `h4`.
I've also added an `aria-describedby` on the username links, pointing to the contributor's title. This means that if someone is tabbing through the contributor links while using a screenreader, if they choose to _linger_ on a link, it will announce their title as supplementary information: `Holben888, link, Supreme Slinkity Stan`. More info at https://benmyers.dev/blog/aria-labels-and-descriptions/
=> Accessibility for contributors table

packages/slinkity/utils/consts.js, packages/slinkity/utils/consts.test.js
Adds a simple passing unit test for `utils/consts:toSSRComment`.
Unit test core functionality #21
=> Add utils.consts:toSSRComment unit test

packages/slinkity/utils/resolveConfigFilePath.test.js
This adds a couple unit tests for `resolveConfigFilePath`.
Unit test core functionality #21
=> Add resolveConfigFilePath unit tests

packages/slinkity/cli/vite.js, packages/slinkity/cli/vite.test.js
This adds passing unit tests for `cli/vite`.
Unit test core functionality #21
=> Add cli/vite unit tests

packages/slinkity/eleventyConfig/addComponentPages.js
Working towards #55
- Add config for adding component pages as extensions
- All-new logic for processing props. `getProps` is no more! Will deserve documentation when this feature is confirmed
=> Feat: add component pages config

packages/slinkity-renderer-react/package-lock.json, packages/slinkity-renderer-react/package.json, packages/slinkity-renderer-vue/StaticHtml.js, packages/slinkity-renderer-vue/client.js, packages/slinkity-renderer-vue/index.js, packages/slinkity-renderer-vue/package-lock.json, packages/slinkity-renderer-vue/package.json, packages/slinkity-renderer-vue/server.js, packages/slinkity/eleventyConfig/__snapshots__/applyViteHtmlTransform.test.js.snap, packages/slinkity/eleventyConfig/addComponentShortcodes.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js
Resolves #12 🥳 
- created a new `@slinkity/renderer-vue` package that's ready to publish
- fixed the `@slinkity/renderer-react` dependencies while I was at it! Discovered the combo of `peerDeps` and `devDeps` we need for framework-specific code from [Vite's Vue plugin](https://github.com/vitejs/vite/blob/main/packages/plugin-vue/package.json). Thought we should use that same pattern across the board going forward
- removed that `__keywords` prop from `addComponentShortcodes`. Seems that prop sneaks in on the `...vargs` spread. This prevents Vue warnings about unexpected props
=> Feat: add Vue renderer

packages/slinkity-renderer-react/StaticHtml.js, packages/slinkity-renderer-react/index.js, packages/slinkity-renderer-vue/StaticHtml.js, packages/slinkity-renderer-vue/index.js, packages/slinkity-renderer-vue/server.js, packages/slinkity/cli/types.d.ts, packages/slinkity/eleventyConfig/addComponentPages.js, packages/slinkity/eleventyConfig/addComponentShortcodes.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js
Resolves #155 
- `toComponentByShortcode` was introduced as a renderer configuration option to open the door for _any_ component framework to support shortcodes! This utility is meant to wrap the string of HTML generated by a shortcode with a component, using the framework's implementation to set inner HTML.
- `handleSSRComments` is now _recursive._ This is meant to support shortcodes that hydrate other components. First, render the page itself, then render any shortcodes generated by that page.
- set up a makeshift example in Vue to prove out the concept further. Left a TODO to refine prop passing, but it should work well as a tech demo in the meantime
=> Feat: support shortcodes in JSX templates

packages/slinkity-renderer-svelte/index.js, packages/slinkity-renderer-svelte/package-lock.json, packages/slinkity-renderer-svelte/package.json, packages/slinkity-renderer-svelte/server.js, packages/slinkity/cli/eleventy.js, packages/slinkity/cli/toViteSSR.js, packages/slinkity/cli/vite.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.test.js, packages/slinkity/eleventyConfig/index.js, packages/slinkity/eleventyConfig/types.d.ts, packages/slinkity/package-lock.json, packages/slinkity/package.json
- Node modules as rollup entrypoints are now resolved to `node_modules`. This is accomplished with a regex under the `viteBuild` function
- Svelte component styles now injected via `<style>` tags. This is due to a limitation with production builds: if you don't hydrate a component, you can't load that component's styles via the `style` tag (as you might with Vue). Ideally, we'd inject styles into the `head` like so to allow shared stylesheets between pages: `<script type="module" src="/Users/me/slinkity-site/src/_includes/Slinky.svelte?svelte&type=style&lang.css"></script>`
- The `env` was changed from `dev | prod` to `development | production`. This was a super in-the-weeds issue with Vue style compilation, where failing to use the string "production" would break style scoping in …
=> Fix: 0.6.0 production builds

packages/slinkity-renderer-react/index.js, packages/slinkity-renderer-react/package-lock.json, packages/slinkity-renderer-react/package.json, packages/slinkity-renderer-svelte/index.js, packages/slinkity-renderer-svelte/package-lock.json, packages/slinkity-renderer-svelte/package.json, packages/slinkity-renderer-vue/index.js, packages/slinkity-renderer-vue/package-lock.json, packages/slinkity-renderer-vue/package.json, packages/slinkity/build.js
Remove usages of `path.join` across 1) renderer package names and 2) our esbuild script
=> Fix: Windows path resolution

packages/create-slinkity/cli.js, packages/create-slinkity/package.json, packages/slinkity-renderer-react/client.js, packages/slinkity-renderer-react/index.js, packages/slinkity-renderer-react/package.json, packages/slinkity-renderer-svelte/index.js, packages/slinkity-renderer-svelte/package.json, packages/slinkity-renderer-vue/index.js, packages/slinkity-renderer-vue/package.json, packages/slinkity/build.js, packages/slinkity/client/eagerLoader.js, packages/slinkity/client/lazyLoader.js, packages/slinkity/eleventyConfig/__snapshots__/applyViteHtmlTransform.test.js.snap, packages/slinkity/eleventyConfig/addComponentShortcodes.js, packages/slinkity/eleventyConfig/addComponentShortcodes.test.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.test.js, packages/slinkity/eleventyConfig/componentAttrStore.js, packages/slinkity/eleventyConfig/index.js, packages/slinkity/eleventyConfig/toLoaderScript.js, packages/slinkity/package.json, pnpm-lock.yaml, www/package.json
Resolves #171 
- Update `create-slinkity` to generate our new `component` shortcode
- Update all renderer `client.js` files to properly slot in children
- Introduce a paired shortcode under `addComponentShortcodes` for children: `slottedComponent`
- Update our docs to use Slinkity version from workspace and 11ty 1.0 (for testing purposes)
=> Feat: support children with new component shortcode

packages/slinkity-renderer-react/index.js, packages/slinkity-renderer-react/package.json, packages/slinkity/eleventyConfig/addComponentPages.js, packages/slinkity/eleventyConfig/addComponentShortcodes.js, pnpm-lock.yaml
- add warnings when using the "render" prop
- add warning when using "getProps" on React component pages
=> Fix: instructional logs to upgrade "render" -> "hydrate"

pnpm-lock.yaml, www/.eleventy.js, www/package.json, www/src/_includes/toc.njk, www/src/_layouts/docs.njk, www/styles/_generic.scss, www/styles/_settings.scss, www/styles/_tools.scss, www/styles/chunks/_toc.scss, www/styles/docs.scss, www/styles/styles.scss
closes #104 
- Adds a TOC!
- Increases the wrapper width to 1200px from previously 1024px
The plugin used provides a filter that runs over the entirety of the content and includes all headlines that have an id set. The current configuration will include headlines from `<h1>` to `<h6>`, _but_ we currently only run `markdown-it-anchor` on `<h2>`& `<h3>`. This means, that if we wanted to include deeper levels of headlines, we'd just have to change the `markdown-it-anchor` config to include more levels. All of this is done comfortably from `.eleventy.js`.
Here are some screenshots:
We don't have a design for this, so this was done on the fly. Any visual feedback is _very_ welcome.
=> Docs: Table of Contents

packages/slinkity-renderer-react/StaticHtml.js, packages/slinkity-renderer-react/index.js, packages/slinkity-renderer-react/package.json, packages/slinkity-renderer-vue/StaticHtml.js, packages/slinkity-renderer-vue/index.js, packages/slinkity-renderer-vue/package.json, packages/slinkity-renderer-vue/server.js, packages/slinkity/cli/types.d.ts, packages/slinkity/eleventyConfig/addComponentPages.js, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js, packages/slinkity/package.json
This _reverts_ our support for JSX-ified shortcodes as described in #155. This deserves an RFC and further community discussion to land on the right formatting, especially to make these shortcodes-as-components usable across frameworks.
- revert PR to support shortcodes-as-components
- expose the "raw" filters and shortcodes (11ty's `javascriptFunctions`) via the `__functions` prop
- expose from dynamic permalink functions
- expose from `hydrate.props()`
- expose on non-hydrated component data
=> Fix: expose shortcodes and filters via `__functions`

README.md, packages/slinkity/README.md, packages/slinkity/package.json, www/src/_includes/value-props.md, www/src/docs/index.md, www/src/docs/quick-start.md
- updated "features" table with renderers support 🎉
- update value proposition to use `component` shortcode, mention other component frameworks
- update `GlassCounter` walkthrough to include Vue and Svelte
=> Docs: quick start updates

packages/slinkity/cli/vite.js
This should resolve #187 as @Holben888 suggested to try. I'll confirm that this alone actually ends up fixing the issue later today when I get back home, but wanted to get the PR with the fix up ASAP so I don't forget about making this contribution. Thanks Ben for all of your hard work on Slinkity and extremely informative videos that you've made on partial hydration, custom client-side routing without a SPA framework, etc! I really like the approach Slinkity uses and am excited to try and start hacking on the updates to my personal portfolio site that I've been wanting to make for years now 😃 (and from one Ben to another, you've got a solid first name 😎)
=> Fix 0.5.0 error requiring react-dom, react as deps

www/src/_includes/Tabs.svelte, www/src/_includes/currentTabStore.js, www/src/docs/component-shortcodes.md, www/styles/_base.scss
- update `Tabs.svelte` to support multiple tab stores
- update styles for `hr` breaks
- rewrite component shortcode docs from the ground up with new features
=> Docs: new component shortcodes

packages/slinkity/cli/index.js, www/src/docs/asset-management.md
This PR adds the exposure of `intermediateDir`(eg. `.11ty-build-DcNVBN`) to `process.env.ELEVENTY_BUILD_OUTPUT_DIR`. 
This is mainly used for Eleventy Image integration and makes https://github.com/slinkity/slinkity/issues/74#issuecomment-1003030190 possible.
=> Expose slinkity's intermediateDir to a `process.env` variable

packages/slinkity/client/toMountPointById.js, packages/slinkity/eleventyConfig/__snapshots__/applyViteHtmlTransform.test.js.snap, packages/slinkity/eleventyConfig/applyViteHtmlTransform.js, packages/slinkity/utils/consts.js
Slinkity renders a mount point around rendered components. I'm using Svelte and the component is rendered in a `react-mount-point`. This works, but is not that great. This PR renames `slinkity-react-mount-point` to `slinkity-mount-point`.
=> Rename `slinkity-react-mount-point` to `slinkity-mount-point`

.changeset/strong-geese-explode.md, packages/create-slinkity/cli.js, packages/create-slinkity/template/.eleventy.js, packages/create-slinkity/template/package.json, packages/create-slinkity/template/src/deployment.md, www/src/docs/deployment.md
- Update `create-slinkity` command to use new Slinkity 0.8 dependency
- Remove `slinkity.config.js` generation, and write the plugin declaration to the 11ty config
- Update deployment instructions to use plain `eleventy` CLI
=> Feat: create slinkity updates

.changeset/proud-moles-refuse.md, packages/slinkity/plugin.js
Previously we assigned the `text/plain` content type regardless of existing headers. This is very dangerous for non-html assets that rely on correct content types.
Now, we only apply the header override to the `__vite_ping` file. This was the only problematic file when paired with 11ty serverless in my testing
=> Fix: only apply `text/plain` content type to `vite_ping`

package.json, pnpm-lock.yaml
I've been hitting some PNPM x Husky issues recently ([see related help threads](https://github.com/pnpm/pnpm/issues/4790)). After some investigation, I've decided to remove Husky and `lint-staged` as a pre-commit hook.
Enforcing pre-commit flows makes rapid debugging more difficult in my opinion; lint errors should not disrupt your workflow. Given the incompatibility between pnpm and husky users are reporting ([even on the latest husky version](https://github.com/pnpm/pnpm/issues/4790#issuecomment-1173665709)), removing should be the simplest. Don't worry, lint checks remain on all PR workflows!
=> Chore: remove husky and lint-staged

www/styles/docs.scss
Safari 16.1 (18614.2.9.1.12)
macOS Ventura 13.0 (22A380)
Before changes:
After changes:
=> fix docs logo wrapping in Webkit
