slinkity/slinkity

package-lock.json
package.json
src/cli.js
src/plugin.js
src/plugins/reactPlugin/_slinkity-react-renderer.js
src/plugins/reactPlugin/index.js
src/utils/concurrentlyByArgvs.js
src/utils/htmlEscape.js
src/utils/parseSimpleShellCmd.js

While this does introduce the use of some undocumented (but still public) APIs in `concurrently`, it also significantly reduces the chance for bugs in the earlier shell-escaping implementation, especially on Windows, where the escaping might have been demonstrably incorrect.
This PR adds a dependency on `cross-spawn`.

Smooth out edge cases, including Windows support

---

.eslintrc.yaml
.github/workflows/ci.yml
.gitignore
.npmignore
.vscode/extensions.json
package-lock.json
package.json
src/cli.js
src/eleventy-wrapper.js
src/plugins/reactPlugin/_slinkity-react-renderer.js
src/plugins/reactPlugin/index.js
src/plugins/reactPlugin/toCommonJSModule.js
src/plugins/sassPlugin/index.js
src/plugins/viteBuildPlugin/index.js
src/utils/concurrentlyByArgvs.js

- add `eslintrc`
- add `lint` and `lint:fix` as scripts
- setup GitHub action to run the linter and check the build for every PR

Feat: Add linting

---

docs/src/docs/component-pages-layouts.md
docs/src/docs/docs.11tydata.js
docs/src/docs/partial-hydration.md
docs/src/docs/quick-start.md
src/plugin/reactPlugin/index.js
src/plugin/reactPlugin/toFormattedDataForProps.js

Feat: New API for "getProps"

---

src/plugin/reactPlugin/__snapshots__/applyHtmlWrapper.test.js.snap
src/plugin/reactPlugin/applyHtmlWrapper.js
src/plugin/reactPlugin/applyHtmlWrapper.test.js
src/plugin/reactPlugin/index.js

Apply <html> and <body> wrappers to route fragments

---

package-lock.json
package.json
src/plugin/reactPlugin/addShortcode.js
src/plugin/reactPlugin/addShortcode.test.js

- adds `faker` as a dev dependency for tests
- adds unit tests for argsArrayToPropsObj
Working towards #21

Add testing - argsArrayToPropsObj

---

src/plugin/reactPlugin/__snapshots__/toHydrationLoadersApplied.test.js.snap
src/plugin/reactPlugin/__snapshots__/toRendererHtml.test.jsx.snap
src/plugin/reactPlugin/_client/_eager-loader.js
src/plugin/reactPlugin/_client/_lazy-loader.js
src/plugin/reactPlugin/_client/_renderer.js
src/plugin/reactPlugin/addShortcode.js
src/plugin/reactPlugin/componentAttrStore.js
src/plugin/reactPlugin/index.js
src/plugin/reactPlugin/toHydrationLoadersApplied.js
src/plugin/reactPlugin/toHydrationLoadersApplied.test.js
src/plugin/reactPlugin/toLoaderScript.js
src/plugin/reactPlugin/toRendererHtml.js
src/plugin/reactPlugin/toRendererHtml.test.jsx
src/utils/consts.js
src/utils/logger.js

28 - Rework internal component to props map

---

package-lock.json
package.json
src/plugin/reactPlugin/addShortcode.js
src/plugin/reactPlugin/index.js
src/plugin/reactPlugin/toCommonJSModule.js
src/plugin/reactPlugin/toHydrationLoadersApplied.js
src/plugin/reactPlugin/toRendererHtml.js

Resolves #13 
Note: this does _not_ support SASS modules!

Feat: add CSS Modules support

---

docs/package-lock.json
docs/package.json

+ removes `eleventy-plugin-sass` as a devDependency.
+ adds `sass` as a dependency.

Remove eleventy-plugin-sass

---

src/plugin/reactPlugin/__snapshots__/toHydrationLoadersApplied.test.js.snap
src/plugin/reactPlugin/addShortcode.js
src/plugin/reactPlugin/componentAttrStore.js
src/plugin/reactPlugin/index.js
src/plugin/reactPlugin/toHydrationLoadersApplied.js
src/plugin/reactPlugin/toHydrationLoadersApplied.test.js

Fix: Load CSS modules for static (non-hydrated) components

---

docs/src/_data/twitterAccounts.yaml

Add Anthony as a Maintainer

---

package-lock.json
package.json

Fix: parsing error on SVG when using node-html-parser v4

---

docs/src/docs/docs.11tydata.js
docs/src/docs/import-aliases.md

Docs: explain import aliases

---

docs/src/docs/component-shortcodes.md
src/plugin/reactPlugin/1-pluginDefinitions/addShortcode.js

Feat: support named shortcode args

---

docs/src/docs/component-shortcodes.md
docs/src/docs/quick-start.md

Docs - remove `/components` dir requirement for shortcodes

---

package-lock.json
package.json
src/plugin/applyViteHtmlTransform.js
src/plugin/index.js

Fix: Vite live reloading on windows

---

www/src/docs/quick-start.md

Correcting the word "defaults".
BTW, I'm loving this project!

Correct typo

---

packages/slinkity/utils/toSlashesTrimmed.js
packages/slinkity/utils/toSlashesTrimmed.test.js

This adds a passing unit test for `toSlashesTrimmed`.
Unit test core functionality #21

Add toSlashesTrimmed unit test

---

packages/slinkity/eleventyConfig/addComponentPages.js

Fix: dynamic permalinks on component pages

---

.eslintrc.yaml
packages/slinkity-renderer-svelte/Wrapper.svelte
packages/slinkity-renderer-svelte/Wrapper.svelte.ssr.js
packages/slinkity-renderer-svelte/client.js
packages/slinkity-renderer-svelte/index.js
packages/slinkity-renderer-svelte/package-lock.json
packages/slinkity-renderer-svelte/package.json
packages/slinkity-renderer-svelte/server.js
packages/slinkity/eleventyConfig/applyViteHtmlTransform.js

Feat: Add Svelte renderer

---

packages/create-slinkity/cli.js
packages/create-slinkity/template/package.json
packages/create-slinkity/template/src/_includes/layout.njk
packages/create-slinkity/template/src/index.md

Feat: `create-slinkity` remaining updates for multi-framework support

---

packages/slinkity/cli/eleventy.js
packages/slinkity/cli/index.js

fixes https://github.com/slinkity/slinkity/issues/154 
As port is not in eleventyArgs, it has been ignored..
I also defined the default port value directly in the option.

fix cli --port issue

---

www/src/_layouts/docs.njk
www/src/docs/docs.11tydata.js
www/styles/_base.scss
www/styles/_generic.scss
www/styles/_settings.scss
www/styles/_tools.scss
www/styles/chunks/_contributor.scss
www/styles/docs.scss

closes #102 
+ Apply the small design change from the docs to the navigation.
+ Add a burger.
+ Hide the navigation menu on smaller screens, accessible via burger.

Collapse the docs navigation into a burger menu on small breakpoints

---

www/src/_layouts/base.njk
www/styles/docs.scss

closes #165
- Change the theme color to match the background.
- Add a mediaquery to make sure that the visual fix that aligns external links vertically doesn't cause unwanted horizontal scrollbars.

Fix unwanted horizontal scrollbars; Replace the theme color

---

packages/slinkity/eleventyConfig/addComponentShortcodes.js

Also includes some helpful console messages:
- deprecated warning on "react" shortcode
- error on missing file extensions after migrating to "component"

Fix: Add back the "react" shortcode for backwards compat

---

www/src/docs/config.md

Fixed config.md docs stating DEBUG=Eleventy* limitation

update: 11ty DEBUG=Eleventy* limitation

---

www/styles/docs.scss

191 Fix an issue related to z-index; Make the mobile top navigation sticky

---

packages/slinkity/eleventyConfig/index.js

Fix: avoid caching pages without an outputPath

---

www/src/docs/quick-start.md

fix: udpate link in docs

---

netlify.toml

fixes https://github.com/slinkity/slinkity/issues/176

Improve Netlify deploy config

---

www/src/_layouts/docs.njk
www/styles/docs.scss

fix: accessibility enhancements

---

README.md
pnpm-lock.yaml

Fix: README "partial hydration" link
